package:
  name: gdal
  version: 2.1.1

source:
  fn: gdal-2.1.1.tar.gz                                         [unix]
  url: http://download.osgeo.org/gdal/2.1.1/gdal-2.1.1.tar.gz   [unix]
  md5: 2a7037c5b30063cecfa104a562c9c07e                         [unix]

requirements:
  build:
    - python
    - numpy          [unix]
    - hdf5           [unix]
    - libnetcdf      [unix]
    - libtiff        [unix]
  run:
    - python
    - numpy
    - hdf5           [unix]
    - libnetcdf      [unix]
    - libtiff        [unix]

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo                [not win]
    - osgeo._gdal_array    [not win]

about:
  home: http://www.gdal.org/
  license: MIT
  summary: 'GDAL: Geospatial Data Abstraction Library'
